engines:
    eslint:
        enabled: false
    duplication:
        enabled: true
        config:
            languages:
                - javascript
    fixme:
        enabled: true
ratings:
    paths:
        - "src/**.js"
        - "specs/**.js"
